[PATH]
data_path  = 'data/'
model_path = 'model/'
plot_path  = 'plot/'
res_path   = 'out/'

[PARAMETERS]
MIN = 2000                  # minimum number of heuristic iteration
MAX = 5000                  # maximum number of heuristic iteration
m   = [3,4,5]               # number of machine poll
n   = [20, 30, 40, 50]      # number of job poll
nnc = 3                     # Number of New Column to add after pricing